import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  root: {
    flex: 1,
  },
  header: {
    borderBottomWidth: 1,
    position: 'relative',
    zIndex: 100,
    elevation: 20,
  },
  desktopTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 16,
  },
  logoWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoImage: {
    width: 40,
    height: 40,
    borderRadius: 4,
  },
  logoText: {
    fontSize: 30,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  desktopButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  userPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  userPillText: {
    fontSize: 13,
    fontFamily: 'Courier',
    fontWeight: '700',
  },
  themeButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  desktopNavRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: 16,
    paddingBottom: 12,
    zIndex: 110,
  },
  navWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    flex: 1,
  },
  dropdownContainer: {
    position: 'relative',
    zIndex: 120,
  },
  dropdownMenu: {
    position: 'absolute',
    top: 52,
    left: 0,
    width: 220,
    borderWidth: 1,
    borderRadius: 16,
    padding: 8,
    zIndex: 130,
    elevation: 30,
  },
  dropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  dropdownItemText: {
    fontSize: 14,
    fontFamily: 'Courier',
  },
  headerButton: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerButtonInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerButtonText: {
    fontSize: 14,
    fontFamily: 'Courier',
  },
  searchBlock: {
    width: 320,
  },
  searchFieldWrap: {
    position: 'relative',
  },
  searchInput: {
    width: '100%',
    borderWidth: 1,
    borderRadius: 999,
    paddingLeft: 16,
    paddingRight: 44,
    paddingVertical: 14,
    fontSize: 14,
    fontFamily: 'Courier',
  },
  searchIcon: {
    position: 'absolute',
    top: 14,
    right: 14,
  },
  suggestionsBox: {
    position: 'absolute',
    top: 52,
    left: 0,
    right: 0,
    borderWidth: 1,
    borderRadius: 14,
    paddingVertical: 6,
    zIndex: 30,
  },
  suggestionItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  suggestionText: {
    fontFamily: 'Courier',
    fontSize: 14,
  },
  mobileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  mobileBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mobileLogoText: {
    fontSize: 28,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  mobileActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mobileThemeButton: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileMenuButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileSearchWrap: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  drawerOverlay: {
    flex: 1,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  drawerPanel: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 320,
    borderLeftWidth: 1,
    padding: 20,
  },
  drawerScrollContent: {
    paddingBottom: 20,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  drawerTitle: {
    fontSize: 28,
    fontFamily: 'Courier',
    fontWeight: '700',
  },
  drawerCloseButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerSection: {
    gap: 12,
    marginBottom: 20,
  },
  drawerGroup: {
    gap: 10,
  },
  drawerGroupTitle: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  drawerSubButton: {
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  drawerSubButtonText: {
    fontSize: 14,
    fontFamily: 'Courier',
  },
  mobileDrawerButton: {
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  scrollContent: {
    flexGrow: 1,
  },
  mainContainer: {
    padding: 24,
    zIndex: 0,
    gap: 24,
  },
  pageStack: {
    gap: 24,
  },
  homePageStack: {
    gap: 24,
  },
  heroGrid: {
    flexDirection: 'row',
    gap: 24,
  },
  stackedGrid: {
    flexDirection: 'column',
  },
  heroPanel: {
    flex: 1.4,
    borderWidth: 1,
    borderRadius: 28,
    padding: 28,
  },
  heroEyebrow: {
    marginBottom: 12,
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Courier',
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: 40,
    lineHeight: 44,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  heroCopy: {
    marginTop: 16,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Courier',
  },
  homeSideStack: {
    flex: 1,
    gap: 16,
  },
  infoCard: {
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
  },
  infoCardTitle: {
    marginBottom: 6,
    fontSize: 15,
    fontFamily: 'Courier',
    fontWeight: '600',
  },
  infoCardCopy: {
    fontSize: 15,
    lineHeight: 24,
    fontFamily: 'Courier',
  },
  featureLinks: {
    flexDirection: 'row',
    gap: 16,
  },
  featureCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
  },
  contentGrid: {
    flexDirection: 'row',
    gap: 24,
    alignItems: 'flex-start',
  },
  pageCard: {
    borderWidth: 1,
    borderRadius: 24,
    padding: 24,
  },
  wordCard: {
    flex: 1.2,
    borderWidth: 1,
    borderRadius: 24,
    padding: 24,
  },
  wordCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  wordDate: {
    fontFamily: 'Courier',
    marginBottom: 8,
  },
  wordCardWord: {
    marginTop: 6,
    fontSize: 34,
    fontWeight: '700',
    fontFamily: 'Courier',
    textTransform: 'capitalize',
  },
  wordCardMeaning: {
    marginTop: 12,
    fontSize: 18,
    lineHeight: 28,
    fontFamily: 'Courier',
  },
  ctaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 18,
  },
  primaryActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 999,
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  secondaryActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  secondaryActionText: {
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  wordTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  wordDetailCard: {
    maxWidth: 1100,
    alignSelf: 'center',
    width: '100%',
    marginVertical: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  wordDetailLayout: {
    flexDirection: 'column',
    gap: 20,
  },
  wordDetailLayoutWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  wordImageWrap: {
    width: '100%',
    maxWidth: 320,
    borderWidth: 1,
    borderRadius: 16,
    overflow: 'hidden',
    alignSelf: 'center',
  },
  wordImage: {
    width: '100%',
    aspectRatio: 1,
  },
  wordDetailContent: {
    flex: 1,
  },
  detailWordTitle: {
    fontSize: 38,
    fontWeight: '700',
    color: '#3b82f6',
    fontFamily: 'Courier',
    textTransform: 'capitalize',
  },
  pronunciation: {
    marginBottom: 14,
    fontFamily: 'Courier',
    fontSize: 18,
  },
  pronunciationSmall: {
    marginBottom: 12,
    fontFamily: 'Courier',
    fontSize: 16,
  },
  wordDetailGrid: {
    flexDirection: 'column',
    gap: 12,
  },
  wordDetailGridWide: {
    flexDirection: 'row',
  },
  wordDetailColumn: {
    flex: 1,
    gap: 12,
  },
  infoBlock: {
    gap: 4,
  },
  infoTitle: {
    fontWeight: '700',
    fontSize: 18,
    fontFamily: 'Courier',
  },
  infoValue: {
    fontSize: 16,
    lineHeight: 22,
    fontFamily: 'Courier',
  },
  pageWrap: {
    maxWidth: 1100,
    width: '100%',
    alignSelf: 'center',
  },
  listPageTitle: {
    fontSize: 34,
    fontWeight: '700',
    fontFamily: 'Courier',
    marginBottom: 16,
  },
  wordListStack: {
    gap: 16,
  },
  subjectCard: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 16,
  },
  emptyState: {
    fontSize: 18,
    fontFamily: 'Courier',
    textAlign: 'center',
    marginVertical: 40,
  },
  paginationBar: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 12,
  },
  rowsPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rowsLabel: {
    fontSize: 14,
    fontFamily: 'Courier',
    fontWeight: '700',
  },
  rowsOption: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  rowsOptionText: {
    fontSize: 14,
    fontFamily: 'Courier',
    fontWeight: '700',
  },
  paginationActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  pagePill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  paginationText: {
    fontSize: 16,
    fontFamily: 'Courier',
  },
  sectionTitle: {
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '700',
    fontFamily: 'Courier',
  },
  sectionCopy: {
    marginTop: 10,
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Courier',
  },
  textPage: {
    maxWidth: 980,
    alignSelf: 'center',
    width: '100%',
    gap: 14,
  },
  aboutTitle: {
    fontSize: 36,
    fontWeight: '700',
    fontFamily: 'Courier',
    marginBottom: 8,
  },
  aboutParagraph: {
    fontSize: 16,
    lineHeight: 26,
    fontFamily: 'Courier',
  },
  shareCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    padding: 16,
    gap: 12,
  },
  shareTextArea: {
    minHeight: 160,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: 'Courier',
    textAlignVertical: 'top',
  },
  shareIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 18,
  },
  quizCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    padding: 20,
    gap: 12,
  },
  quizCardTitle: {
    fontSize: 18,
    fontFamily: 'Courier',
    fontWeight: '700',
  },
  quizHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  quizAction: {
    justifyContent: 'space-between',
  },
  authGrid: {
    alignItems: 'stretch',
  },
  authIntroCard: {
    maxWidth: 420,
  },
  authCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 14,
    padding: 20,
    gap: 12,
  },
  authInput: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: 'Courier',
  },
  authSubmit: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  authSubmitText: {
    fontFamily: 'Courier',
    fontSize: 15,
    fontWeight: '700',
  },
  authSwitch: {
    fontFamily: 'Courier',
    fontSize: 15,
    fontWeight: '700',
  },
  authSwitchButton: {
    alignSelf: 'flex-start',
  },
  hiddenTitle: {
    position: 'absolute',
    opacity: 0,
    fontSize: 1,
  },
});
